import type { Plugin } from "../../_shared/model.ts"

const reactPlugin = (): Plugin => ({
  jsPlugins: ["eslint-plugin-react-x"],
  overrides: [
    {
      files: ["**/*.{stories,test,spec}.{jsx,tsx,js,ts}"],
      rules: {
        "react/jsx-props-no-spreading": "off",
      },
    },
  ],
  plugins: ["react", "jsx-a11y"],
  rules: {
    "jsx_a11y/alt-text": "error",
    "jsx_a11y/anchor-ambiguous-text": "error",
    "jsx_a11y/anchor-has-content": "error",
    "jsx_a11y/anchor-is-valid": "error",
    "jsx_a11y/aria-activedescendant-has-tabindex": "error",
    "jsx_a11y/aria-props": "error",
    "jsx_a11y/aria-proptypes": "error",
    "jsx_a11y/aria-role": "error",
    "jsx_a11y/aria-unsupported-elements": "error",
    "jsx_a11y/autocomplete-valid": "error",
    "jsx_a11y/click-events-have-key-events": "error",
    "jsx_a11y/control-has-associated-label": [
      "off",
      {
        ignoreElements: ["audio", "canvas", "embed", "input", "textarea", "tr", "video"],
        ignoreRoles: [
          "grid",
          "listbox",
          "menu",
          "menubar",
          "radiogroup",
          "row",
          "tablist",
          "toolbar",
          "tree",
          "treegrid",
        ],
        includeRoles: ["alert", "dialog"],
      },
    ],
    "jsx_a11y/heading-has-content": "error",
    "jsx_a11y/html-has-lang": "error",
    "jsx_a11y/iframe-has-title": "error",
    "jsx_a11y/img-redundant-alt": "error",
    "jsx_a11y/interactive-supports-focus": [
      "error",
      {
        tabbable: ["button", "checkbox", "link", "searchbox", "spinbutton", "switch", "textbox"],
      },
    ],
    "jsx_a11y/label-has-associated-control": "error",
    "jsx_a11y/lang": "error",
    "jsx_a11y/media-has-caption": "error",
    "jsx_a11y/mouse-events-have-key-events": "error",
    "jsx_a11y/no-access-key": "error",
    "jsx_a11y/no-aria-hidden-on-focusable": "error",
    "jsx_a11y/no-autofocus": ["error", { ignoreNonDOM: true }],
    "jsx_a11y/no-distracting-elements": "error",
    "jsx_a11y/no-interactive-element-to-noninteractive-role": [
      "error",
      {
        canvas: ["img"],
        tr: ["none", "presentation"],
      },
    ],
    "jsx_a11y/no-noninteractive-element-interactions": [
      "error",
      {
        alert: ["onKeyUp", "onKeyDown", "onKeyPress"],
        body: ["onError", "onLoad"],
        dialog: ["onKeyUp", "onKeyDown", "onKeyPress"],
        handlers: [
          "onClick",
          "onError",
          "onLoad",
          "onMouseDown",
          "onMouseUp",
          "onKeyPress",
          "onKeyDown",
          "onKeyUp",
        ],
        iframe: ["onError", "onLoad"],
        img: ["onError", "onLoad"],
      },
    ],
    "jsx_a11y/no-noninteractive-element-to-interactive-role": [
      "error",
      {
        fieldset: ["radiogroup", "presentation"],
        li: ["menuitem", "option", "row", "tab", "treeitem"],
        ol: ["listbox", "menu", "menubar", "radiogroup", "tablist", "tree", "treegrid"],
        table: ["grid"],
        td: ["gridcell"],
        ul: ["listbox", "menu", "menubar", "radiogroup", "tablist", "tree", "treegrid"],
      },
    ],
    "jsx_a11y/no-noninteractive-tabindex": [
      "error",
      {
        allowExpressionValues: true,
        roles: ["tabpanel"],
        tags: [],
      },
    ],
    "jsx_a11y/no-redundant-roles": "error",
    "jsx_a11y/no-static-element-interactions": [
      "error",
      {
        allowExpressionValues: true,
        handlers: ["onClick", "onMouseDown", "onMouseUp", "onKeyPress", "onKeyDown", "onKeyUp"],
      },
    ],
    "jsx_a11y/prefer-tag-over-role": "error",
    "jsx_a11y/role-has-required-aria-props": "error",
    "jsx_a11y/role-supports-aria-props": "error",
    "jsx_a11y/scope": "error",
    "jsx_a11y/tabindex-no-positive": "error",

    /**
     * eslint-plugin-react-x rules
     * https://npmx.dev/package/eslint-plugin-react-x
     */

    "react-x/error-boundaries": "error",
    "react-x/globals": "error",
    "react-x/immutability": "error",
    "react-x/no-nested-component-definitions": "error",
    "react-x/no-nested-lazy-component-declarations": "error",
    "react-x/purity": "error",
    "react-x/refs": "error",
    "react-x/set-state-in-effect": "error",
    "react-x/set-state-in-render": "error",
    "react-x/static-components": "error",
    "react-x/unsupported-syntax": "error",
    "react-x/use-memo": "error",

    // These rules are covered by built-in react rules:

    "react-x/exhaustive-deps": "off",
    "react-x/no-array-index-key": "off",
    "react-x/no-clone-element": "off",
    "react-x/no-direct-mutation-state": "off",
    "react-x/rules-of-hooks": "off",

    // All other react-x rules off until we've had time to go through them,
    // assess them for usefulness and cross reference them with Oxlint built-in rules.

    "react-x/no-access-state-in-setstate": "off",
    "react-x/no-children-count": "off",
    "react-x/no-children-for-each": "off",
    "react-x/no-children-map": "off",
    "react-x/no-children-only": "off",
    "react-x/no-children-to-array": "off",
    "react-x/no-class-component": "off",
    "react-x/no-component-will-mount": "off",
    "react-x/no-component-will-receive-props": "off",
    "react-x/no-component-will-update": "off",
    "react-x/no-context-provider": "off",
    "react-x/no-create-ref": "off",
    "react-x/no-duplicate-key": "off",
    "react-x/no-forward-ref": "off",
    "react-x/no-implicit-children": "off",
    "react-x/no-implicit-key": "off",
    "react-x/no-implicit-ref": "off",
    "react-x/no-leaked-conditional-rendering": "off",
    "react-x/no-missing-component-display-name": "off",
    "react-x/no-missing-context-display-name": "off",
    "react-x/no-missing-key": "off",
    "react-x/no-misused-capture-owner-stack": "off",
    "react-x/no-set-state-in-component-did-mount": "off",
    "react-x/no-set-state-in-component-did-update": "off",
    "react-x/no-set-state-in-component-will-update": "off",
    "react-x/no-unnecessary-use-prefix": "off",
    "react-x/no-unsafe-component-will-mount": "off",
    "react-x/no-unsafe-component-will-receive-props": "off",
    "react-x/no-unsafe-component-will-update": "off",
    "react-x/no-unstable-context-value": "off",
    "react-x/no-unstable-default-props": "off",
    "react-x/no-unused-class-component-members": "off",
    "react-x/no-unused-props": "off",
    "react-x/no-unused-state": "off",
    "react-x/no-use-context": "off",
    "react-x/use-state": "off",

    /**
     * Built in React rules.
     */

    "react/button-has-type": "error",
    "react/checked-requires-onchange-or-readonly": "error",
    "react/display-name": "error",
    "react/exhaustive-deps": "error",
    "react/forbid-component-props": "off",
    "react/forbid-dom-props": "error",
    "react/forbid-elements": "error",
    "react/forward-ref-uses-ref": "error",
    "react/hook-use-state": "error",
    "react/iframe-missing-sandbox": "error",
    "react/jsx-boolean-value": "error",
    "react/jsx-curly-brace-presence": "error",
    "react/jsx-filename-extension": [
      "error",
      {
        extensions: [".jsx", ".tsx"],
      },
    ],
    "react/jsx-fragments": "error",
    "react/jsx-handler-names": "error",
    "react/jsx-key": "error",
    "react/jsx-max-depth": "off",
    "react/jsx-no-comment-textnodes": "error",
    "react/jsx-no-constructed-context-values": "error",
    "react/jsx-no-duplicate-props": "error",
    "react/jsx-no-script-url": "error",
    "react/jsx-no-target-blank": "error",
    "react/jsx-no-undef": "error",
    "react/jsx-no-useless-fragment": [
      "error",
      {
        allowExpressions: true,
      },
    ],
    "react/jsx-pascal-case": [
      "error",
      {
        allowAllCaps: true,
      },
    ],
    "react/jsx-props-no-spread-multi": "error",
    "react/jsx-props-no-spreading": [
      "error",
      {
        custom: "enforce",
        explicitSpread: "ignore",
        html: "enforce",
      },
    ],
    "react/no-array-index-key": "error",
    "react/no-children-prop": "error",
    "react/no-clone-element": "error",
    "react/no-danger": "error",
    "react/no-danger-with-children": "error",
    "react/no-did-mount-set-state": "error",
    "react/no-did-update-set-state": "error",
    "react/no-direct-mutation-state": "error",
    "react/no-find-dom-node": "error",
    "react/no-is-mounted": "error",
    "react/no-multi-comp": "off",
    "react/no-namespace": "error",
    "react/no-object-type-as-default-prop": "error",
    "react/no-react-children": "error",
    "react/no-redundant-should-component-update": "error",
    "react/no-render-return-value": "error",
    "react/no-set-state": "error",
    "react/no-string-refs": "error",
    "react/no-this-in-sfc": "error",
    "react/no-unescaped-entities": "error",
    "react/no-unknown-property": "error",
    "react/no-unsafe": "error",
    "react/no-unstable-nested-components": [
      "error",
      {
        // Also matches Button's `popover` prop because the rule doesn't find
        // the nested object prop: `popover.renderContent`.
        propNamePattern: "{popover,render*}",
      },
    ],
    "react/no-will-update-set-state": "error",
    "react/only-export-components": "off",
    "react/prefer-es6-class": "error",
    "react/prefer-function-component": ["error", { allowJsxUtilityClass: true }],
    "react/react-in-jsx-scope": "off",
    "react/require-render-return": "error",
    "react/rules-of-hooks": "error",
    "react/self-closing-comp": "error",
    "react/state-in-constructor": "error",
    "react/style-prop-object": "error",
    "react/void-dom-elements-no-children": "error",
  },
  settings: {},
})

export default reactPlugin
