import type { FullOxlintConfig, Options } from './model.ts'

import { ensureInstalled } from './ensure-installed.ts'
import { emptyOxlintConfig } from './model.ts'

export const reactConfig = (options: Options | undefined): FullOxlintConfig => {
  if (!options?.react) return emptyOxlintConfig

  return {
    ...emptyOxlintConfig,
    jsPlugins: [
      {
        name: 'react-js',
        specifier: ensureInstalled('eslint-plugin-react'),
      },
    ],
    overrides: [
      {
        files: ['**/*.{stories,test,spec}.{jsx,tsx,js,ts}'],
        rules: {
          'react/jsx-props-no-spreading': 'off',
        },
      },
    ],
    plugins: ['react', 'jsx-a11y'],
    rules: {
      'jsx_a11y/alt-text': 'error',
      'jsx_a11y/anchor-ambiguous-text': 'error',
      'jsx_a11y/anchor-has-content': 'error',
      'jsx_a11y/anchor-is-valid': 'error',
      'jsx_a11y/aria-activedescendant-has-tabindex': 'error',
      'jsx_a11y/aria-props': 'error',
      'jsx_a11y/aria-proptypes': 'error',
      'jsx_a11y/aria-role': 'error',
      'jsx_a11y/aria-unsupported-elements': 'warn',
      'jsx_a11y/autocomplete-valid': 'error',
      'jsx_a11y/click-events-have-key-events': 'error',
      'jsx_a11y/control-has-associated-label': 'off',
      'jsx_a11y/heading-has-content': 'error',
      'jsx_a11y/html-has-lang': 'error',
      'jsx_a11y/iframe-has-title': 'error',
      'jsx_a11y/img-redundant-alt': 'error',
      'jsx_a11y/interactive-supports-focus': [
        'error',
        {
          tabbable: ['button', 'checkbox', 'link', 'searchbox', 'spinbutton', 'switch', 'textbox'],
        },
      ],
      'jsx_a11y/label-has-associated-control': 'error',
      'jsx_a11y/lang': 'error',
      'jsx_a11y/media-has-caption': 'error',
      'jsx_a11y/mouse-events-have-key-events': 'error',
      'jsx_a11y/no-access-key': 'error',
      'jsx_a11y/no-aria-hidden-on-focusable': 'warn',
      'jsx_a11y/no-autofocus': ['error', { ignoreNonDOM: true }],
      'jsx_a11y/no-distracting-elements': 'error',
      'jsx_a11y/no-interactive-element-to-noninteractive-role': [
        'error',
        {
          canvas: ['img'],
          tr: ['none', 'presentation'],
        },
      ],
      'jsx_a11y/no-noninteractive-element-interactions': [
        'error',
        {
          alert: ['onKeyUp', 'onKeyDown', 'onKeyPress'],
          body: ['onError', 'onLoad'],
          dialog: ['onKeyUp', 'onKeyDown', 'onKeyPress'],
          handlers: [
            'onClick',
            'onError',
            'onLoad',
            'onMouseDown',
            'onMouseUp',
            'onKeyPress',
            'onKeyDown',
            'onKeyUp',
          ],
          iframe: ['onError', 'onLoad'],
          img: ['onError', 'onLoad'],
        },
      ],
      'jsx_a11y/no-noninteractive-element-to-interactive-role': [
        'error',
        {
          fieldset: ['radiogroup', 'presentation'],
          li: ['menuitem', 'option', 'row', 'tab', 'treeitem'],
          ol: ['listbox', 'menu', 'menubar', 'radiogroup', 'tablist', 'tree', 'treegrid'],
          table: ['grid'],
          td: ['gridcell'],
          ul: ['listbox', 'menu', 'menubar', 'radiogroup', 'tablist', 'tree', 'treegrid'],
        },
      ],
      'jsx_a11y/no-noninteractive-tabindex': [
        'error',
        {
          allowExpressionValues: true,
          roles: ['tabpanel'],
          tags: [],
        },
      ],
      'jsx_a11y/no-redundant-roles': 'warn',
      'jsx_a11y/no-static-element-interactions': [
        'error',
        {
          allowExpressionValues: true,
          handlers: ['onClick', 'onMouseDown', 'onMouseUp', 'onKeyPress', 'onKeyDown', 'onKeyUp'],
        },
      ],
      'jsx_a11y/prefer-tag-over-role': 'error',
      'jsx_a11y/role-has-required-aria-props': 'error',
      'jsx_a11y/role-supports-aria-props': 'error',
      'jsx_a11y/scope': 'warn',
      'jsx_a11y/tabindex-no-positive': 'error',

      /**
       * eslint-plugin-react rules
       * https://npmx.dev/package/eslint-plugin-react
       */

      'react-js/no-unused-prop-types': 'error',

      // All other react-js rules off; check if built-in or react-x supports a
      // required linting rule first as these are more performant.

      'react-js/boolean-prop-naming': 'off',
      'react-js/button-has-type': 'off',
      'react-js/checked-requires-onchange-or-readonly': 'off',
      'react-js/default-props-match-prop-types': 'off',
      'react-js/destructuring-assignment': 'off',
      'react-js/display-name': 'off',
      'react-js/forbid-component-props': 'off',
      'react-js/forbid-dom-props': 'off',
      'react-js/forbid-elements': 'off',
      'react-js/forbid-foreign-prop-types': 'off',
      'react-js/forbid-prop-types': 'off',
      'react-js/forward-ref-uses-ref': 'off',
      'react-js/function-component-definition': 'off',
      'react-js/hook-use-state': 'off',
      'react-js/iframe-missing-sandbox': 'off',
      'react-js/jsx-boolean-value': 'off',
      'react-js/jsx-child-element-spacing': 'off',
      'react-js/jsx-closing-bracket-location': 'off',
      'react-js/jsx-closing-tag-location': 'off',
      'react-js/jsx-curly-brace-presence': 'off',
      'react-js/jsx-curly-newline': 'off',
      'react-js/jsx-curly-spacing': 'off',
      'react-js/jsx-equals-spacing': 'off',
      'react-js/jsx-filename-extension': 'off',
      'react-js/jsx-first-prop-new-line': 'off',
      'react-js/jsx-fragments': 'off',
      'react-js/jsx-handler-names': 'off',

      'react-js/jsx-indent': 'off',
      'react-js/jsx-indent-props': 'off',
      'react-js/jsx-key': 'off',
      'react-js/jsx-max-depth': 'off',
      'react-js/jsx-max-props-per-line': 'off',
      'react-js/jsx-newline': 'off',
      'react-js/jsx-no-bind': 'off',
      'react-js/jsx-no-comment-textnodes': 'off',
      'react-js/jsx-no-constructed-context-values': 'off',
      'react-js/jsx-no-duplicate-props': 'off',
      'react-js/jsx-no-leaked-render': 'off',
      'react-js/jsx-no-literals': 'off',
      'react-js/jsx-no-script-url': 'off',
      'react-js/jsx-no-target-blank': 'off',
      'react-js/jsx-no-undef': 'off',
      'react-js/jsx-no-useless-fragment': 'off',
      'react-js/jsx-one-expression-per-line': 'off',
      'react-js/jsx-pascal-case': 'off',
      'react-js/jsx-props-no-multi-spaces': 'off',
      'react-js/jsx-props-no-spread-multi': 'off',
      'react-js/jsx-props-no-spreading': 'off',
      'react-js/jsx-sort-default-props': 'off',
      'react-js/jsx-sort-props': 'off',
      'react-js/jsx-space-before-closing': 'off',
      'react-js/jsx-tag-spacing': 'off',
      'react-js/jsx-uses-react': 'off',
      'react-js/jsx-uses-vars': 'off',
      'react-js/jsx-wrap-multilines': 'off',
      'react-js/no-access-state-in-setstate': 'off',
      'react-js/no-adjacent-inline-elements': 'off',
      'react-js/no-array-index-key': 'off',
      'react-js/no-arrow-function-lifecycle': 'off',
      'react-js/no-children-prop': 'off',
      'react-js/no-danger': 'off',
      'react-js/no-danger-with-children': 'off',
      'react-js/no-deprecated': 'off',
      'react-js/no-did-mount-set-state': 'off',
      'react-js/no-did-update-set-state': 'off',
      'react-js/no-direct-mutation-state': 'off',
      'react-js/no-find-dom-node': 'off',
      'react-js/no-invalid-html-attribute': 'off',
      'react-js/no-is-mounted': 'off',
      'react-js/no-multi-comp': 'off',
      'react-js/no-namespace': 'off',
      'react-js/no-object-type-as-default-prop': 'off',
      'react-js/no-redundant-should-component-update': 'off',
      'react-js/no-render-return-value': 'off',
      'react-js/no-set-state': 'off',
      'react-js/no-string-refs': 'off',
      'react-js/no-this-in-sfc': 'off',
      'react-js/no-typos': 'off',
      'react-js/no-unescaped-entities': 'off',
      'react-js/no-unknown-property': 'off',
      'react-js/no-unsafe': 'off',
      'react-js/no-unstable-nested-components': 'off',
      'react-js/no-unused-class-component-methods': 'off',
      'react-js/no-unused-state': 'off',
      'react-js/no-will-update-set-state': 'off',
      'react-js/prefer-es6-class': 'off',
      'react-js/prefer-exact-props': 'off',
      'react-js/prefer-read-only-props': 'off',
      'react-js/prefer-stateless-function': 'off',
      'react-js/prop-types': 'off',
      'react-js/react-in-jsx-scope': 'off',
      'react-js/require-default-props': 'off',
      'react-js/require-optimization': 'off',
      'react-js/require-render-return': 'off',
      'react-js/self-closing-comp': 'off',
      'react-js/sort-comp': 'off',
      'react-js/sort-default-props': 'off',

      'react-js/sort-prop-types': 'off',
      'react-js/state-in-constructor': 'off',
      'react-js/static-property-placement': 'off',
      'react-js/style-prop-object': 'off',
      'react-js/void-dom-elements-no-children': 'off',

      /**
       * Built in React rules.
       */

      'react/button-has-type': 'error',
      'react/checked-requires-onchange-or-readonly': 'error',
      'react/display-name': 'error',
      'react/exhaustive-deps': 'error',
      'react/forbid-component-props': 'off',
      'react/forbid-dom-props': 'error',
      'react/forbid-elements': 'error',
      'react/forward-ref-uses-ref': 'error',
      'react/function-component-definition': [
        'error',
        { namedComponents: 'arrow-function', unnamedComponents: 'arrow-function' },
      ],
      'react/hook-use-state': 'error',
      'react/iframe-missing-sandbox': 'error',
      'react/jsx-boolean-value': 'warn',
      'react/jsx-curly-brace-presence': 'warn',
      'react/jsx-filename-extension': [
        'error',
        {
          extensions: ['.jsx', '.tsx'],
        },
      ],
      'react/jsx-fragments': 'warn',
      'react/jsx-handler-names': 'error',
      'react/jsx-key': 'error',
      'react/jsx-max-depth': 'off',
      'react/jsx-no-comment-textnodes': 'error',
      'react/jsx-no-constructed-context-values': 'error',
      'react/jsx-no-duplicate-props': 'error',
      'react/jsx-no-literals': 'off',
      'react/jsx-no-script-url': 'error',
      'react/jsx-no-target-blank': 'error',
      'react/jsx-no-undef': 'error',
      'react/jsx-no-useless-fragment': [
        'error',
        {
          allowExpressions: true,
        },
      ],
      'react/jsx-pascal-case': [
        'error',
        {
          allowAllCaps: true,
        },
      ],
      'react/jsx-props-no-spread-multi': 'warn',
      'react/jsx-props-no-spreading': [
        'error',
        {
          custom: 'enforce',
          explicitSpread: 'ignore',
          html: 'enforce',
        },
      ],
      'react/no-array-index-key': 'error',
      'react/no-children-prop': 'error',
      'react/no-clone-element': 'error',
      'react/no-danger': 'error',
      'react/no-danger-with-children': 'error',
      'react/no-did-mount-set-state': 'error',
      'react/no-did-update-set-state': 'error',
      'react/no-direct-mutation-state': 'error',
      'react/no-find-dom-node': 'error',
      'react/no-is-mounted': 'error',
      'react/no-multi-comp': 'off',
      'react/no-namespace': 'error',
      'react/no-object-type-as-default-prop': 'error',
      'react/no-react-children': 'error',
      'react/no-redundant-should-component-update': 'error',
      'react/no-render-return-value': 'error',
      'react/no-set-state': 'error',
      'react/no-string-refs': 'error',
      'react/no-this-in-sfc': 'error',
      'react/no-unescaped-entities': 'error',
      'react/no-unknown-property': 'error',
      'react/no-unsafe': 'error',
      'react/no-unstable-nested-components': [
        'error',
        {
          // Also matches Button's `popover` prop because the rule doesn't find
          // the nested object prop: `popover.renderContent`.
          propNamePattern: '{popover,render*}',
        },
      ],
      'react/no-will-update-set-state': 'error',
      'react/only-export-components': 'off',
      'react/prefer-es6-class': 'error',
      'react/prefer-function-component': ['error', { allowJsxUtilityClass: true }],
      'react/react-compiler': ['error', { reportAllBailouts: true }],
      'react/react-in-jsx-scope': 'off',
      'react/require-render-return': 'error',
      'react/rules-of-hooks': 'error',
      'react/self-closing-comp': 'warn',
      'react/state-in-constructor': 'error',
      'react/style-prop-object': 'error',
      'react/void-dom-elements-no-children': 'error',
    },
    settings: {},
  }
}
