import type { DummyRule } from "oxlint"

export const rulesUnicorn: Record<string, DummyRule> = {
  "unicorn/catch-error-name": "warn",
  "unicorn/consistent-assert": "warn",
  "unicorn/consistent-date-clone": "warn",
  "unicorn/consistent-empty-array-spread": "error",
  "unicorn/consistent-existence-index-check": "warn",
  "unicorn/consistent-function-scoping": ["error", { checkArrowFunctions: false }],
  "unicorn/consistent-template-literal-escape": "warn",
  "unicorn/custom-error-definition": "error",
  "unicorn/empty-brace-spaces": "warn",
  "unicorn/error-message": "error",
  "unicorn/escape-case": "warn",
  // Don't care how blah.length is checked.
  "unicorn/explicit-length-check": "off",
  "unicorn/filename-case": [
    "error",
    {
      cases: {
        kebabCase: true,
        pascalCase: true,
      },
    },
  ],
  // Not sure if this is useful yet.
  "unicorn/import-style": "off",
  "unicorn/new-for-builtins": "error",
  "unicorn/no-abusive-eslint-disable": "error",
  "unicorn/no-accessor-recursion": "error",
  "unicorn/no-anonymous-default-export": "error",
  "unicorn/no-array-callback-reference": "off",
  "unicorn/no-array-for-each": "error",
  "unicorn/no-array-method-this-argument": "error",
  "unicorn/no-array-reduce": "error",
  "unicorn/no-array-reverse": "warn",
  "unicorn/no-array-sort": "warn",
  "unicorn/no-await-expression-member": "error",
  "unicorn/no-await-in-promise-methods": "error",
  "unicorn/no-console-spaces": "warn",
  "unicorn/no-document-cookie": "error",
  "unicorn/no-empty-file": "error",
  "unicorn/no-hex-escape": "warn",
  "unicorn/no-immediate-mutation": "error",
  "unicorn/no-instanceof-array": "warn",
  "unicorn/no-instanceof-builtins": "error",
  "unicorn/no-invalid-fetch-options": "error",
  "unicorn/no-invalid-remove-event-listener": "error",
  "unicorn/no-length-as-slice-end": "warn",
  "unicorn/no-lonely-if": "error",
  "unicorn/no-magic-array-flat-depth": "error",
  "unicorn/no-negated-condition": "error",
  "unicorn/no-negation-in-equality-check": "error",
  // Nested ternaries can be useful.
  "unicorn/no-nested-ternary": "off",
  "unicorn/no-new-array": "error",
  "unicorn/no-new-buffer": "error",
  "unicorn/no-null": "off",
  "unicorn/no-object-as-default-parameter": "error",
  "unicorn/no-process-exit": "error",
  "unicorn/no-single-promise-in-promise-methods": "error",
  "unicorn/no-static-only-class": "error",
  "unicorn/no-thenable": "error",
  "unicorn/no-this-assignment": "error",
  "unicorn/no-typeof-undefined": "error",
  "unicorn/no-unnecessary-array-flat-depth": "error",
  "unicorn/no-unnecessary-array-splice-count": "warn",
  "unicorn/no-unnecessary-await": "error",
  "unicorn/no-unnecessary-slice-end": "warn",
  "unicorn/no-unreadable-array-destructuring": "error",
  "unicorn/no-unreadable-iife": "error",
  "unicorn/no-useless-collection-argument": "error",
  "unicorn/no-useless-error-capture-stack-trace": "error",
  "unicorn/no-useless-fallback-in-spread": "error",
  "unicorn/no-useless-iterator-to-array": "error",
  "unicorn/no-useless-length-check": "error",
  "unicorn/no-useless-promise-resolve-reject": "warn",
  "unicorn/no-useless-spread": "error",
  "unicorn/no-useless-switch-case": "error",
  "unicorn/no-useless-undefined": "warn",
  "unicorn/no-zero-fractions": "warn",
  "unicorn/number-literal-case": "warn",
  "unicorn/numeric-separators-style": "warn",
  "unicorn/prefer-add-event-listener": "error",
  "unicorn/prefer-array-find": "error",
  "unicorn/prefer-array-flat": "error",
  "unicorn/prefer-array-flat-map": "warn",
  "unicorn/prefer-array-index-of": "error",
  "unicorn/prefer-array-some": "error",
  "unicorn/prefer-at": "error",
  "unicorn/prefer-bigint-literals": "warn",
  "unicorn/prefer-blob-reading-methods": "error",
  "unicorn/prefer-class-fields": "error",
  "unicorn/prefer-classlist-toggle": "warn",
  "unicorn/prefer-code-point": "warn",
  "unicorn/prefer-date-now": "warn",
  "unicorn/prefer-default-parameters": "warn",
  "unicorn/prefer-dom-node-append": "warn",
  "unicorn/prefer-dom-node-dataset": "error",
  "unicorn/prefer-dom-node-remove": "error",
  "unicorn/prefer-dom-node-text-content": "error",
  "unicorn/prefer-event-target": "error",
  // Could be too disruptive to a lot of projects using `window`.
  "unicorn/prefer-global-this": "off",
  "unicorn/prefer-import-meta-properties": "warn",
  "unicorn/prefer-includes": "error",
  "unicorn/prefer-keyboard-event-key": "warn",
  "unicorn/prefer-logical-operator-over-ternary": "error",
  "unicorn/prefer-math-min-max": "warn",
  "unicorn/prefer-math-trunc": "error",
  "unicorn/prefer-modern-dom-apis": "error",
  "unicorn/prefer-modern-math-apis": "error",
  "unicorn/prefer-module": "off",
  "unicorn/prefer-native-coercion-functions": "error",
  "unicorn/prefer-negative-index": "warn",
  "unicorn/prefer-node-protocol": "warn",
  "unicorn/prefer-number-properties": "error",
  "unicorn/prefer-object-from-entries": "error",
  "unicorn/prefer-optional-catch-binding": "warn",
  "unicorn/prefer-prototype-methods": "warn",
  "unicorn/prefer-query-selector": "error",
  "unicorn/prefer-reflect-apply": "error",
  "unicorn/prefer-regexp-test": "warn",
  "unicorn/prefer-response-static-json": "error",
  "unicorn/prefer-set-has": "error",
  "unicorn/prefer-set-size": "warn",
  "unicorn/prefer-spread": "error",
  // Double escaping is quite common and using `String.raw` is quite verbose.
  "unicorn/prefer-string-raw": "off",
  "unicorn/prefer-string-replace-all": "off",
  "unicorn/prefer-string-slice": "error",
  "unicorn/prefer-string-starts-ends-with": "warn",
  "unicorn/prefer-string-trim-start-end": "warn",
  "unicorn/prefer-structured-clone": "off",
  "unicorn/prefer-ternary": ["error", "only-single-line"],
  "unicorn/prefer-top-level-await": "off",
  "unicorn/prefer-type-error": "warn",
  "unicorn/relative-url-style": "error",
  "unicorn/require-array-join-separator": "error",
  "unicorn/require-module-attributes": "error",
  "unicorn/require-module-specifiers": "warn",
  "unicorn/require-number-to-fixed-digits-argument": "warn",
  "unicorn/require-post-message-target-origin": "error",
  "unicorn/switch-case-braces": ["warn", "avoid"],
  "unicorn/switch-case-break-position": "error",
  "unicorn/text-encoding-identifier-case": "warn",
  "unicorn/throw-new-error": "warn",
}
