import type { DummyRule } from 'oxlint'

import restrictedGlobals from 'confusing-browser-globals'

export const rulesEslint: Record<string, DummyRule> = {
  'accessor-pairs': 'error',
  'array-callback-return': [
    'error',
    // To be compatible with unicorn/no-useless-undefined
    { allowImplicit: true },
  ],
  'arrow-body-style': 'off',
  'block-scoped-var': 'error',
  'capitalized-comments': 'off',
  'class-methods-use-this': 'off',
  complexity: 'off',
  'constructor-super': 'error',
  curly: 'off',
  'default-case': 'error',
  'default-case-last': 'error',
  'default-param-last': 'error',
  eqeqeq: 'error',
  'for-direction': 'error',
  'func-name-matching': 'error',
  'func-names': ['error', 'as-needed'],
  'func-style': ['error', 'declaration', { allowArrowFunctions: true }],
  'getter-return': 'error',
  'grouped-accessor-pairs': 'error',
  'guard-for-in': 'error',
  'id-length': 'off',
  'id-match': 'off',
  'init-declarations': 'off',
  'logical-assignment-operators': 'off',
  'max-classes-per-file': 'off',
  'max-depth': 'off',
  'max-lines': 'off',
  'max-lines-per-function': 'off',
  'max-nested-callbacks': 'error',
  'max-params': 'off',
  'max-statements': 'off',
  'new-cap': [
    'error',
    {
      capIsNewExceptions: [
        'After',
        'AfterAll',
        'AfterStep',
        'Before',
        'BeforeAll',
        'BeforeStep',
        'DataTable',
        'Given',
        'Then',
        'When',
        'World',
      ],
    },
  ],
  'no-alert': 'error',
  'no-array-constructor': 'warn',
  'no-async-promise-executor': 'error',
  'no-await-in-loop': 'error',
  'no-bitwise': 'error',
  'no-caller': 'error',
  'no-case-declarations': 'error',
  'no-class-assign': 'error',
  'no-compare-neg-zero': 'error',
  'no-cond-assign': 'error',
  'no-console': 'error',
  'no-const-assign': 'error',
  'no-constant-binary-expression': 'error',
  'no-constant-condition': 'error',
  'no-constructor-return': 'error',
  'no-continue': 'error',
  'no-control-regex': 'error',
  'no-debugger': 'error',
  'no-delete-var': 'error',
  'no-div-regex': 'warn',
  'no-dupe-class-members': 'error',
  'no-dupe-else-if': 'error',
  'no-dupe-keys': 'error',
  'no-duplicate-case': 'error',
  // Use import-x instead.
  'no-duplicate-imports': 'off',
  'no-else-return': 'error',
  'no-empty': 'error',
  'no-empty-character-class': 'error',
  'no-empty-function': 'error',
  'no-empty-pattern': 'error',
  'no-empty-static-block': 'error',
  'no-eq-null': 'error',
  'no-eval': 'error',
  'no-ex-assign': 'error',
  'no-extend-native': 'error',
  'no-extra-bind': 'error',
  'no-extra-boolean-cast': 'error',
  'no-extra-label': 'warn',
  'no-fallthrough': ['error', { allowEmptyCase: true }],
  'no-func-assign': 'error',
  'no-global-assign': 'error',
  'no-implicit-coercion': 'warn',
  'no-implicit-globals': 'error',
  'no-implied-eval': 'error',
  'no-import-assign': 'error',
  'no-inline-comments': 'error',
  'no-inner-declarations': 'error',
  'no-invalid-regexp': 'error',
  'no-irregular-whitespace': 'error',
  'no-iterator': 'error',
  'no-label-var': 'error',
  'no-labels': 'error',
  'no-lone-blocks': 'error',
  'no-lonely-if': 'error',
  'no-loop-func': 'error',
  'no-loss-of-precision': 'error',
  'no-magic-numbers': 'off',
  'no-misleading-character-class': 'error',
  'no-multi-assign': 'error',
  'no-multi-str': 'error',
  // This is handled by unicorn.
  'no-negated-condition': 'off',
  'no-nested-ternary': 'off',
  'no-new': 'error',
  'no-new-func': 'error',
  'no-new-native-nonconstructor': 'error',
  'no-new-wrappers': 'warn',
  'no-nonoctal-decimal-escape': 'error',
  'no-obj-calls': 'error',
  'no-object-constructor': 'error',
  'no-param-reassign': 'error',
  'no-plusplus': 'error',
  'no-promise-executor-return': 'error',
  'no-proto': 'error',
  'no-prototype-builtins': 'error',
  'no-redeclare': 'error',
  'no-regex-spaces': 'warn',
  'no-restricted-exports': 'off',
  // The ESLint browser environment defines all browser globals as valid,
  // even though most people don't know some of them exist (e.g. `name` or
  // `status`). This is dangerous as it hides accidentally undefined
  // variables. We blacklist the globals that we deem potentially
  // confusing. To use them, explicitly reference them, e.g. `window.name`
  // or `window.status`.
  'no-restricted-globals': ['error', ...restrictedGlobals],
  'no-restricted-imports': 'off',
  'no-restricted-properties': 'off',
  'no-return-assign': 'error',
  'no-script-url': 'error',
  'no-self-assign': 'error',
  'no-self-compare': 'error',
  'no-sequences': 'error',
  'no-setter-return': 'error',
  'no-shadow': 'error',
  'no-shadow-restricted-names': 'error',
  'no-sparse-arrays': 'error',
  'no-template-curly-in-string': 'error',
  'no-ternary': 'off',
  'no-this-before-super': 'error',
  'no-throw-literal': 'error',
  'no-unassigned-vars': 'error',
  'no-undef': 'error',
  'no-undefined': 'off',
  'no-underscore-dangle': 'off',
  'no-unexpected-multiline': 'off',
  'no-unmodified-loop-condition': 'error',
  'no-unneeded-ternary': 'error',
  'no-unreachable': 'error',
  'no-unsafe-finally': 'error',
  'no-unsafe-negation': 'warn',
  'no-unsafe-optional-chaining': 'error',
  'no-unused-expressions': 'error',
  'no-unused-labels': 'warn',
  'no-unused-private-class-members': 'error',
  'no-unused-vars': [
    'error',
    {
      // Useful for extracting args from props and ignoring them:
      // { style: _style, ...restProps }
      argsIgnorePattern: '^_',
      varsIgnorePattern: '[iI]gnored',
    },
  ],
  'no-use-before-define': 'error',
  'no-useless-assignment': 'error',
  'no-useless-backreference': 'off',
  'no-useless-call': 'error',
  'no-useless-catch': 'error',
  'no-useless-computed-key': 'error',
  'no-useless-concat': 'error',
  'no-useless-constructor': 'error',
  'no-useless-escape': 'warn',
  'no-useless-rename': 'warn',
  'no-useless-return': 'error',
  'no-var': 'error',
  'no-void': 'error',
  'no-warning-comments': 'off',
  'no-with': 'error',
  'object-shorthand': ['warn', 'always', { ignoreConstructors: true }],
  'operator-assignment': ['error', 'never'],
  'prefer-arrow-callback': ['warn', { allowNamedFunctions: true }],
  'prefer-const': 'error',
  'prefer-destructuring': [
    'error',
    {
      AssignmentExpression: {
        array: false,
        object: false,
      },
      VariableDeclarator: {
        // Make compatible with Unicorn's no-unreadable-array-destructuring.
        array: false,
        object: true,
      },
    },
  ],
  'prefer-exponentiation-operator': 'warn',
  'prefer-named-capture-group': 'off',
  'prefer-numeric-literals': 'error',
  'prefer-object-has-own': 'error',
  'prefer-object-spread': 'warn',
  'prefer-promise-reject-errors': 'error',
  'prefer-regex-literals': 'error',
  'prefer-rest-params': 'error',
  'prefer-spread': 'error',
  'prefer-template': 'warn',
  'preserve-caught-error': 'error',
  radix: 'error',
  'require-await': 'error',
  'require-unicode-regexp': 'error',
  'require-yield': 'error',
  // Sorting imports is handled by Perfectionist.
  'sort-imports': 'off',
  'sort-keys': 'off',
  // Not required as one-var rule is set to 'error'; there will never be vars to sort.
  'sort-vars': 'off',
  'symbol-description': 'error',
  'unicode-bom': 'off',
  'use-isnan': 'error',
  'valid-typeof': ['error', { requireStringLiterals: true }],
  'vars-on-top': 'error',
  yoda: 'warn',
}
